spring:
  data:
    mongodb:
      uri: mongodb://test:test@localhost:27017/test?authSource=admin
#      host: localhost
#      port: 27017
#      username: root
#      password: example
#      authentication-database: admin